version: '3.8'

services:
  moodle:
    image: moodlehq/moodle-php-apache:8.1
    container_name: moodle
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/moodledata
      - ./plugins:/var/www/html/local
    environment:
      MOODLE_URL: http://localhost:8080
      MOODLE_DBTYPE: mysqli
      MOODLE_DBHOST: db
      MOODLE_DBNAME: moodle
      MOODLE_DBUSER: moodle
      MOODLE_DBPASS: moodle
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: moodle-db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle

